--- #YAML:1.0
name:               MediaWiki-Bot-Plugin-Steward
version:            0.0.1
abstract:           A plugin to MediaWiki::Bot providing steward functions
author:
    - Mike.lifeguard and the Perlwikibot team
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    HTML::Entities:  1.35
    MediaWiki::Bot:  3.2.0
    Net::CIDR:       0
    URI::Escape:     3.28
    WWW::Mechanize:  1.30
    XML::Simple:     2.16
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
